version: 2
jobs:
  hello_world:
    docker:
      - image: circleci/python:3.5
    steps:
      - checkout
      - run: python3 hello_world.py
  test:
    docker:
      - image: circleci/python:3.5
    steps:
      - checkout
      - run: python3 test.py

workflows:
  version: 2
  hello_then_test:
    jobs:
      - hello_world
      - test:
          requires:
            - hello_world
