version: 2
jobs:
  hello_world:
    docker:
      - image: circleci/python:3.5
    steps:
      - checkout
      - run: python3 hello_world.py
  test:
    docker:
      - image: circleci/python:3.5
    steps:
      - checkout
      - run: python3 test.py

workflows:
  version: 2
  untagged-build:
    jobs:
      - hello_world
  tagged-build:
    jobs:
      - hello_world
      - test:
          filters:
            tags:
              only: /^v.*/
